runtime: python27
api_version: 1
threadsafe : yes
instance_class: B1
basic_scaling:
  max_instances: 2
  idle_timeout: 10m
default_expiration: "1d"

handlers : 
-  url: /sitemaps.xml
   static_files : static/sitemaps.xml
   upload : static/sitemaps.xml
-  url: /manifest.json
   static_files : static/manifest.json
   upload : static/manifest.json
-  url: /favicon.ico
   static_files : static/favicon.png
   upload : static/favicon.png
-  url: /icon-192.png
   static_files : static/icon-192.png
   upload : static/icon-192.png   
-  url: /service-worker.js
   static_files : static/service-worker.js
   upload : static/service-worker.js
   mime_type : application/javascript
-  url: /static
   static_dir: static
-  url: /fonts
   static_dir: fonts
-  url: /
   script : index.app
   login : optional
-  url: /admin/.*
   script: utilitair.app
   login: optional
-  url: /.*
   script: index.app
   login : optional
   
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

  # [START env_variables]
env_variables:
# [END env_variables]