application: partitions
version: 1
runtime: python27
api_version: 1
threadsafe : yes

handlers : 
-  url: /image
   static_dir: image
-  url: /static1
   static_dir: static
-  url: /.*
   script: index.app
   
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest