application: tune-2000
version: 1
runtime: python27
api_version: 1
threadsafe : yes

handlers : 
-  url: /image
   static_dir: image
-  url: /static
   static_dir: static
-  url: /add_tune
   script : index.app
   login : required
-  url: /
   script : index.app
   login : optional
-  url: /.*
   script: index.app
   login : optional
   
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
