application: tune-2000
version: 2
runtime: python27
api_version: 1
threadsafe : yes

default_expiration: "1d"

handlers : 
-  url: /sitemaps.xml
   static_files : static/sitemaps.xml
   upload : static/sitemaps.xml
-  url: /static
   static_dir: static
-  url: /fonts
   static_dir: fonts
-  url: /
   script : index.app
   login : optional
-  url: /.*
   script: index.app
   login : optional
   
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: MySQLdb
  version: "latest"